<?php
session_start();
header('Content-Type: application/json');
require_once '../db_connect.php';

// 1. Check if user is logged in
if (!isset($_SESSION['user_email'])) {
    echo json_encode(['success' => false, 'message' => 'User not logged in.']);
    exit;
}

// 2. Get the data sent from JavaScript
 $input = file_get_contents('php://input');
 $data = json_decode($input, true);

if (!$data || !isset($data['vehicle']) || !isset($data['service']) || !isset($data['price'])) {
    echo json_encode(['success' => false, 'message' => 'Missing booking data.']);
    exit;
}

 $user_email = $_SESSION['user_email'];
 $vehicle = $data['vehicle'];
 $service = $data['service'];
 $time = $data['time'];
 $price = $data['price'];

// 3. Insert into the database
try {
    $stmt = $pdo->prepare("INSERT INTO bookings (user_email, vehicle_details, service_name, est_time, price, status) VALUES (?, ?, ?, ?, ?, 'Pending Payment')");
    $stmt->execute([$user_email, $vehicle, $service, $time, $price]);
    
    $booking_id = $pdo->lastInsertId(); // Get the new ID generated by MySQL
    
    // Return success and the new booking ID to JavaScript
    echo json_encode(['success' => true, 'booking_id' => $booking_id]);

} catch (PDOException $e) {
    echo json_encode(['success' => false, 'message' => 'Database error: ' . $e->getMessage()]);
}
?>